/*
 * generated by Xtext
 */
package eban.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WebifulUiModule extends eban.ui.AbstractWebifulUiModule {
	public WebifulUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
