/*
* generated by Xtext
*/
package eban.ui.contentassist;

import eban.ui.contentassist.AbstractWebifulProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WebifulProposalProvider extends AbstractWebifulProposalProvider {

}
