/*
 * generated by Xtext
 */
package eban;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WebifulRuntimeModule extends eban.AbstractWebifulRuntimeModule {

}
